### ISSUE TITLE
Returns 500 error when file does not exist.

### ISSUE THREAD

**Issue by peterholak** [dirkraft/dropwizard-file-assets#1]
Due to an uncaught exception. It would make more sense to return 404. Also when a directory doesn't have an index file.

**Comment by dirkraft** [comment]
Hi, I was able to fix this. Thanks for reporting something I can actually do.

I went ahead released a 0.0.2 with the fix to maven central. It usually takes about a day for it to show up on central.

**Comment by peterholak** [comment]
Thanks for the fast fix :)
