### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by karussell** [dirkraft/dropwizard-file-assets#3]
Thanks for your work!

Which dropwizard version will work or against which version was it already tested?

As I'm having issues with 1.2.2

I can see the log info ala 

`com.github.dirkraft.dropwizard.fileassets.FileAssetsBundle: Registering FileAssetBundle with servlet name file-assets for request path /maps/* from file system /..../graphhopper/web/src/main/resources/assets`

But I the loading from disc seems not to work and I cannot see any debug information for a request to the assets :(

**Comment by dirkraft** [comment]
build.gradle in the project says 1.0 so I guess that's what version I wrote it against. Have you tried with just `/maps/` (no *) - I don't remember if that makes a difference or not, I do remember figuring out all the path config between jersey and other servlets being confusing.

This code was basically a modification on the original dropwizard AssetBundle to read from the filesystem and never cache files in memory. 

That was awhile ago so I don't remember much about it. Sorry I can't be of more help. I remember I had to fiddle with some path stuff in different ways across different (old) versions of dropwizard to get both my APIs and static assets serving happy.

**Comment by karussell** [comment]
I was already using `/maps/` without *. Will try again. See https://github.com/graphhopper/graphhopper/issues/1330#issuecomment-381346716

**Comment by karussell** [comment]
Stupid me: I did not remove the original asset bundle call

**Comment by dirkraft** [comment]
ah glad you figured it out 😄
